# Generated by Django 5.0.3 on 2024-03-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0002_games_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="games",
            name="is_tournament",
            field=models.BooleanField(default=False),
        ),
    ]
