# Generated by Django 5.0.3 on 2024-03-30 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0003_games_is_tournament"),
    ]

    operations = [
        migrations.AddField(
            model_name="games",
            name="genre",
            field=models.CharField(default="action", max_length=15),
        ),
    ]
