# Generated by Django 5.0.3 on 2024-03-30 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0004_games_genre"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="games",
            name="path",
        ),
        migrations.AddField(
            model_name="games",
            name="is_discount",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="games",
            name="path_to_img",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="games",
            name="path_to_mini_img",
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
