# Generated by Django 5.0.3 on 2024-03-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0005_remove_games_path_games_is_discount_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="games",
            name="is_discount",
        ),
        migrations.AddField(
            model_name="games",
            name="discount",
            field=models.FloatField(default=0.0),
        ),
    ]
