# Generated by Django 5.0.3 on 2024-03-30 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0006_remove_games_is_discount_games_discount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="games",
            old_name="discount",
            new_name="discount_percent",
        ),
    ]
