# Generated by Django 5.0.3 on 2024-03-30 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0007_rename_discount_games_discount_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="games",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
