# Generated by Django 5.0.3 on 2024-04-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0008_games_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="games",
            name="slug",
            field=models.SlugField(blank=True, max_length=100),
        ),
    ]
