# Generated by Django 5.0.3 on 2024-04-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0009_games_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="games",
            name="slug",
            field=models.SlugField(max_length=100, unique=True),
        ),
    ]
