# Generated by Django 5.0.3 on 2024-04-07 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0016_genre_analog_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="games",
            name="genre",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cats",
                to="main_app.genre",
            ),
        ),
    ]
