# Generated by Django 5.0.3 on 2024-04-17 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0019_alter_cover_title"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Info",
            new_name="InfoBuy",
        ),
    ]
