# Generated by Django 5.0.3 on 2024-04-19 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0020_rename_info_infobuy"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="games",
            name="rating",
        ),
    ]
