# Generated by Django 5.0.3 on 2024-04-19 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0022_gameinfo"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GameInfo",
        ),
    ]
