# Generated by Django 5.0.3 on 2024-04-19 18:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0022_gameinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gameinfo",
            name="date_release",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
