# Generated by Django 5.0.3 on 2024-04-19 19:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0023_delete_gameinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path_to_img", models.CharField(blank=True, max_length=100)),
                ("path_to_mini_img", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("features", models.TextField(blank=True)),
                ("date_release", models.DateField(default=django.utils.timezone.now)),
                ("publisher", models.CharField(blank=True, max_length=100)),
                ("developer", models.CharField(blank=True, max_length=100)),
                ("local", models.CharField(blank=True, max_length=100)),
                ("system", models.CharField(blank=True, max_length=100)),
                ("age_rating", models.CharField(blank=True, max_length=3)),
            ],
        ),
        migrations.AddField(
            model_name="games",
            name="gameinfo",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="game",
                to="main_app.gameinfo",
            ),
        ),
    ]
