# Generated by Django 5.0.3 on 2024-04-19 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0024_gameinfo_games_gameinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="games",
            name="gameinfo",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="game",
                to="main_app.gameinfo",
            ),
            preserve_default=False,
        ),
    ]
