# Generated by Django 5.0.3 on 2024-04-20 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0025_alter_games_gameinfo"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinSystemReq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("os", models.CharField(blank=True, max_length=100)),
                ("processor", models.CharField(blank=True, max_length=150)),
                ("memory", models.CharField(blank=True, max_length=150)),
                ("graphics", models.CharField(blank=True, max_length=150)),
                ("storage", models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name="RecSystemReq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("os", models.CharField(blank=True, max_length=100)),
                ("processor", models.CharField(blank=True, max_length=150)),
                ("memory", models.CharField(blank=True, max_length=150)),
                ("graphics", models.CharField(blank=True, max_length=150)),
                ("storage", models.CharField(blank=True, max_length=5)),
            ],
        ),
        migrations.AddField(
            model_name="games",
            name="min_system_req",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="game",
                to="main_app.minsystemreq",
            ),
        ),
        migrations.AddField(
            model_name="games",
            name="recom_system_req",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="game",
                to="main_app.recsystemreq",
            ),
        ),
    ]
