# Generated by Django 5.0.3 on 2024-04-29 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0028_alter_minsystemreq_graphics_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="games",
            name="gameinfo",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="game",
                to="main_app.gameinfo",
            ),
        ),
        migrations.AlterField(
            model_name="games",
            name="min_system_req",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="game",
                to="main_app.minsystemreq",
            ),
        ),
        migrations.AlterField(
            model_name="games",
            name="recom_system_req",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="game",
                to="main_app.recsystemreq",
            ),
        ),
    ]
