# Generated by Django 5.0.3 on 2024-05-06 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0029_alter_games_gameinfo_alter_games_min_system_req_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="games",
            name="description",
        ),
    ]
